Repository ryushin01/sr_novel, pull requests merged in 2024-02, with the labels that each got.

#2 ✨ Component/select box 추가 관련 PR요청
  public/images/select_down_arrow.png
  public/images/select_up_arrow.png
  src/assets/data/ConstantData.jsx
  src/components/SelectBox/SelectBox.jsx
  src/components/SelectBox/SelectBox.scss
  vite.config.js
Labels: documentation

#6 🚑️ Fix/select box 컴포넌트 scss 변경
  src/Router.jsx
  src/assets/data/ApiUrl.jsx
  src/components/SelectBox/SelectBox.scss
  src/pages/BestSeller/BestSeller.jsx
  src/pages/Main/BestBand/BestBand.scss
  src/pages/Main/Components/BestBand/BestBand.jsx
  src/pages/Main/Components/BestBand/BestBand.scss
  src/pages/Main/Components/BigBanner/BigBanner.jsx
  src/pages/Main/Components/BigBanner/BigBanner.scss
  src/pages/Main/Components/NewBook/NewBook.jsx
  src/pages/Main/Components/NewBook/NewBook.scss
  src/pages/Main/Components/NewSpecial/NewSpecial.jsx
  src/pages/Main/Components/NewSpecial/NewSpecial.scss
  src/pages/Main/Main.jsx
  src/pages/Main/Main.scss
  src/svg/right_arrow.svg
  vite.config.js
Labels: 리뷰 요청

#8 🚑️ Fix/main title PR 요청
  src/assets/data/ApiUrl.jsx
  src/components/MainTitle/MainTitle.jsx
  src/components/MainTitle/MainTitle.scss
  src/pages/Main/Components/BestBand/BestBand.jsx
  src/pages/Main/Components/BestBand/BestBand.scss
  src/pages/Main/Components/NewBook/NewBook.scss
  src/pages/Main/Main.jsx
  src/pages/Main/Main.scss
Labels: 리뷰 요청

#9 🎨 UI/main 컴포넌트 분할 및 적용 완료 PR 요청
  src/assets/data/ApiUrl.jsx
  src/pages/Main/Components/BookListItems/BookListItems.jsx
  src/pages/Main/Components/BookListItems/components/ListItemImg.jsx
  src/pages/Main/Components/BookListItems/components/ListItemTitle.jsx
  src/pages/Main/Components/BookListSection/BookListSection.jsx
  src/pages/Main/Components/BookListSection/components/BookList/BookList.jsx
  src/pages/Main/Components/BookListWrapper/BookListWrapper.jsx
  src/pages/Main/Components/BookListWrapperGroup/BookListWrapperGroup.jsx
  src/pages/Main/Components/MainTitle/MainTitle.jsx
  src/pages/Main/Components/MainTitle/MainTitle.scss
  src/pages/Main/Main.jsx
  src/pages/Main/Main.scss
Labels: 리뷰 요청

#10 🎨 UI/main 잔건 수정
  src/pages/Main/Components/BestBand/BestBand.jsx
  src/pages/Main/Components/BestBand/BestBand.scss
  src/pages/Main/Components/BigBanner/BigBanner.jsx
  src/pages/Main/Components/BigBanner/BigBanner.scss
  src/pages/Main/Components/NewBook/NewBook.jsx
  src/pages/Main/Components/NewBook/NewBook.scss
  src/pages/Main/Components/NewSpecial/NewSpecial.jsx
Labels: 리뷰 요청

#11 🚑️ 페이지 삭제에 따른 라우터 수정
  src/Router.jsx
Labels: 리뷰 요청

#12 🎨💄 UI/main 컴포넌트 구조화 변경 및 scss 수정
  src/pages/Main/Components/BookListItems/BookListContents.jsx
  src/pages/Main/Components/BookListItems/BookListItems.jsx
  src/pages/Main/Components/BookListItems/components/ListContentsImg.jsx
  src/pages/Main/Components/BookListItems/components/ListContentsTitle.jsx
  src/pages/Main/Components/BookListSection/components/BookList/BookList.jsx
  src/pages/Main/Main.scss
Labels: 리뷰 요청

#13 💄 뱃지 컴포넌트 개발
  src/components/Badge/Badge.jsx
  src/components/Badge/Badge.scss
  src/components/BadgeGroup/BadgeGroup.jsx
  src/components/BadgeGroup/BadgeGroup.scss
Labels: 리뷰 요청

#14 💄 버튼 컴포넌트 개발
  src/components/Button/Button.jsx
  src/components/Button/Button.scss
Labels: 리뷰 요청

#15 💄 UI/main 북 랭킹 추가
  public/images/main_banner.jpg
  public/images/main_banner_2.jpg
  src/assets/data/ApiUrl.jsx
  src/pages/Main/Components/BookListItems/BookListContents.jsx
  src/pages/Main/Components/BookListItems/components/ListContentsTitle.jsx
  src/pages/Main/Components/BookListSection/BookListSection.jsx
  src/pages/Main/Components/BookListSection/components/BookList/BookList.jsx
  src/pages/Main/Components/BookListWrapperGroup/BookListWrapperGroup.jsx
  src/pages/Main/Main.jsx
  src/pages/Main/Main.scss
Labels: PR 완료

#17 💄 헤더 컴포넌트 개발
  src/assets/scss/partials/typography.scss
  src/components/Header/Header.jsx
  src/components/Header/Header.scss
  src/components/ThemeSwitch/ThemeSwitch.scss
  src/svg/header/icon_search_dark.svg
  src/svg/header/icon_search_light.svg
Labels: 리뷰 요청

#18 💄 푸터 컴포넌트 개발
  src/Router.jsx
  src/assets/scss/partials/typography.scss
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.scss
Labels: 리뷰 요청

#16 🚧 detail Page 1차 UI 완성 PR 요청
  public/images/down_arrow.png
  public/images/ticket.png
  public/images/up_arrow.png
  src/Router.jsx
  src/pages/BookDetail/BookDetail.jsx
  src/pages/BookDetail/BookDetail.scss
  src/pages/BookDetail/components/FilterButton.jsx/FilterButton.jsx
  src/pages/BookDetail/components/ToggleButton/ToggleButton.jsx
  src/pages/Main/Components/BookListItems/components/ListContentsImg.jsx
  src/pages/Main/Components/BookListItems/components/ListContentsTitle.jsx
Labels: 리뷰 요청

#19 📝 상세 데이터 개발(줄거리 제외) 및 명세서 추가
  public/data/DetailData API 명세.md
  public/data/DetailData.json
Labels: PR 완료

#20 📝 상세 데이터 수정
  public/data/DetailData API 명세.md
  public/data/DetailData.json
Labels: PR 완료

#21 🚑️ 버튼 컴포넌트 공백 처리
  src/components/Button/Button.scss
Labels: 리뷰 요청

#22 ✨ UI/detail 2차 UI 완성 PR 요청
  public/images/comments.png
  public/images/dark_theme_32.png
  public/images/like.png
  public/images/rating.png
  public/images/views.png
  src/components/ThemeSwitch/ThemeSwitch.scss
  src/lottie/DataLoading.json
  src/pages/BookDetail/BookDetail.jsx
  src/pages/BookDetail/BookDetail.scss
  src/pages/BookDetail/components/BookDetailInfo/DetailBadge.jsx
  src/pages/BookDetail/components/BookDetailInfo/DetailInfoDescription.jsx
  src/pages/BookDetail/components/BookDetailInfo/DetailInfoEvalWrap.jsx
  src/pages/BookDetail/components/BookDetailInfo/DetailInfoHashtag.jsx
  src/pages/BookDetail/components/BookDetailInfo/DetailInfoPublishWrap.jsx
  src/pages/BookDetail/components/BookDetailInfo/DetailInfoTitleWrap.jsx
  src/pages/BookDetail/components/BookDetailInfoSection/BookDetailInfoSection.jsx
  src/pages/BookDetail/components/BookDetailInfoSection/components/BookDetailInfoWrap.jsx
  src/pages/BookDetail/components/BookDetailInfoSection/components/BookImage.jsx
  src/pages/BookDetail/components/EpisodeListSection/EpisodeListSection.jsx
  src/pages/BookDetail/components/EpisodeListSection/components/EpisodeList.jsx
  src/pages/BookDetail/components/EpisodeListSection/components/EpisodeListItem.jsx
  src/pages/BookDetail/components/EpisodeListSection/components/EpisodeListTitle.jsx
  src/pages/BookDetail/components/FilterButton/FilterButton.jsx
  src/svg/detail/icon_down_arrow_dark.svg
  src/svg/detail/icon_down_arrow_light.svg
  src/svg/detail/icon_ticket_dark.svg
  src/svg/detail/icon_ticket_light.svg
  src/svg/detail/icon_up_arrow_dark.svg
  src/svg/detail/icon_up_arrow_light.svg
Labels: 리뷰 요청

#23 💄 테마 변경 시 화면 정상적으로 표기 되도록 sass 파일 수정
  src/pages/Main/Components/MainTitle/MainTitle.scss
  src/pages/Main/Main.scss
Labels: 리뷰 요청

#25 💄 UI/list 리스트 페이지 UI 완성 1차 PR 요청
  src/Router.jsx
  src/assets/data/ConstantData.jsx
  src/components/Pagination/Pagination.jsx
  src/components/Pagination/Pagination.scss
  src/pages/BestSeller/BestSeller.jsx
  src/pages/BestSeller/BestSeller.scss
  src/pages/List/List.jsx
  src/pages/List/List.scss
  src/pages/Main/Components/BookListSection/BookListSection.jsx
  src/pages/Main/Components/BookListWrapperGroup/BookListWrapperGroup.jsx
  src/pages/Main/Main.jsx
  src/svg/list/icon_backward_arrow_dark.svg
  src/svg/list/icon_backward_arrow_light.svg
  src/svg/list/icon_forward_arrow_dark.svg
  src/svg/list/icon_forward_arrow_light.svg
Labels: 리뷰 요청

#26 💄 회원가입, 로그인 버튼 추가
  src/components/Header/Header.jsx
  src/components/Header/Header.scss
  src/svg/header/icon_signin_dark.svg
  src/svg/header/icon_signin_light.svg
  src/svg/header/icon_signup_dark.svg
  src/svg/header/icon_signup_light.svg
Labels: 리뷰 요청

#27 ✨ UI/login PR 요청
  index.html
  package-lock.json
  package.json
  public/data/LoginData.json
  public/images/icon_close.png
  src/RegExp.jsx
  src/components/CheckBox/CheckBox.jsx
  src/components/CheckBox/CheckBox.scss
  src/components/IconButton/IconButton.jsx
  src/components/IconButton/IconButton.scss
  src/components/Input/Input.jsx
  src/components/Input/Input.scss
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.scss
  src/components/Modal/Portal.jsx
  src/components/Modal/components/LoginModal.jsx
  src/components/Modal/components/LoginModal.scss
  src/config.jsx
  src/customHooks/useInput.jsx
  src/svg/sign/icon_checkbox_checked.svg
  src/svg/sign/icon_checkbox_dark.svg
  src/svg/sign/icon_checkbox_light.svg
  vite.config.js
Labels: 리뷰 요청

#28 🚑️ 다크 테마 변경 시 로그인 아이콘 반전 처리
  src/svg/header/icon_signin_dark.svg
Labels: 리뷰 요청

#31 💄 뷰어 UI 개발
  src/Router.jsx
  src/assets/data/ViewerModeData.jsx
  src/assets/scss/base/common.scss
  src/assets/scss/partials/mixin.scss
  src/assets/scss/partials/viewer_theme.scss
  src/components/BackButton/BackButton.jsx
  src/components/BackButton/BackButton.scss
  src/pages/Viewer/Viewer.jsx
  src/pages/Viewer/Viewer.scss
  src/pages/Viewer/components/ViewerFooter/ViewerFooter.jsx
  src/pages/Viewer/components/ViewerFooter/ViewerFooter.scss
  src/pages/Viewer/components/ViewerHeader/ViewerHeader.jsx
  src/pages/Viewer/components/ViewerHeader/ViewerHeader.scss
  src/pages/Viewer/components/ViewerHeader/components/Radio/Radio.jsx
  src/pages/Viewer/components/ViewerHeader/components/Radio/Radio.scss
  src/pages/Viewer/components/ViewerHeader/components/RadioGroup/RadioGroup.jsx
  src/pages/Viewer/components/ViewerHeader/components/RadioGroup/RadioGroup.scss
  src/pages/Viewer/components/ViewerHeader/components/ViewerModeSwitcher/ViewerModeSwitcher.jsx
  src/pages/Viewer/components/ViewerHeader/components/ViewerModeSwitcher/ViewerModeSwitcher.scss
  src/pages/Viewer/components/ViewerMain/ViewerMain.jsx
  src/pages/Viewer/components/ViewerMain/ViewerMain.scss
  src/pages/Viewer/components/ViewerMain/components/ViewerContent/ViewerContent.jsx
  src/pages/Viewer/components/ViewerMain/components/ViewerContent/ViewerContent.scss
  src/pages/Viewer/components/ViewerMain/components/ViewerMetadata/ViewerMetadata.jsx
  src/pages/Viewer/components/ViewerMain/components/ViewerMetadata/ViewerMetadata.scss
  src/svg/common/icon_arrow_left_dark.svg
  src/svg/common/icon_arrow_left_light.svg
  src/svg/viewer/icon_font.svg
  src/svg/viewer/icon_setting_active.svg
  src/svg/viewer/icon_setting_dark.svg
  src/svg/viewer/icon_setting_light.svg
  src/svg/viewer/icon_theme.svg
Labels: 리뷰 요청

#30 ✨ UI/sign up 회원가입 페이지 UI PR요청
  src/Router.jsx
  src/assets/data/ConstantData.jsx
  src/components/Button/Button.jsx
  src/components/Button/Button.scss
  src/components/CheckBox/CheckBox.scss
  src/components/Header/Header.jsx
  src/components/Input/Input.jsx
  src/components/Input/Input.scss
  src/components/Modal/components/LoginModal.jsx
  src/components/Radio/Radio.jsx
  src/components/Radio/Radio.scss
  src/components/RadioGroup/RadioGroup.jsx
  src/components/RadioGroup/RadioGroup.scss
  src/components/SelectBox/SelectBox.scss
  src/pages/Login/Login.jsx
  src/pages/SignUp/SignUp.jsx
  src/pages/SignUp/SignUp.scss
  src/pages/SignUp/components/FooterBtn.jsx
  src/pages/SignUp/components/SignUpForm.jsx
  src/pages/SignUp/components/TermsOfUse.jsx
  src/pages/SignUp/components/UserInfo.jsx
Labels: PR 완료

#34 ✨ 뷰어 기능 개발
  public/data/DetailData.json
  src/Router.jsx
  src/pages/BookDetail/components/EpisodeListSection/components/EpisodeListItem.jsx
  src/pages/Viewer/Viewer.jsx
  src/pages/Viewer/components/ViewerHeader/ViewerHeader.jsx
  src/pages/Viewer/components/ViewerHeader/ViewerHeader.scss
  src/pages/Viewer/components/ViewerMain/ViewerMain.jsx
  src/pages/Viewer/components/ViewerMain/components/ViewerContent/ViewerContent.jsx
  src/pages/Viewer/components/ViewerMain/components/ViewerContent/ViewerContent.scss
  src/pages/Viewer/components/ViewerMain/components/ViewerMetadata/ViewerMetadata.jsx
  src/pages/Viewer/components/ViewerMain/components/ViewerMetadata/ViewerMetadata.scss
Labels: 리뷰 요청

#35 💄 검색 UI 개발(검색 상세 잔여 작업)
  src/Router.jsx
  src/assets/data/ConstantData.jsx
  src/assets/scss/base/common.scss
  src/pages/Search/Search.jsx
  src/pages/Search/Search.scss
  src/pages/Search/components/RecommendKeywords/RecommendKeywords.jsx
  src/pages/Search/components/RecommendKeywords/RecommendKeywords.scss
  src/pages/Search/components/SearchForm/SearchForm.jsx
  src/pages/Search/components/SearchForm/SearchForm.scss
  src/svg/search/icon_reset_dark.svg
  src/svg/search/icon_reset_light.svg
  src/svg/search/icon_search.svg
Labels: 리뷰 요청

#33 🎨 회원가입 페이지 기능 작업 완료 PR 요청
  public/data/SignUpData.json
  src/RegExp.jsx
  src/components/CheckBox/CheckBox.scss
  src/components/Modal/components/LoginModal.jsx
  src/components/Radio/Radio.jsx
  src/customHooks/useInput.jsx
  src/pages/SignUp/components/SignUpForm.jsx
  src/pages/SignUp/components/TermsOfUse.jsx
  src/pages/SignUp/components/TermsOfUseForm.jsx
  src/pages/SignUp/components/UserInfo.jsx
Labels: PR 완료

#36 💄 Feat/main miniTablet 용 UI코드 수정
  src/Router.jsx
  src/assets/scss/partials/grid_system.scss
  src/components/ScrollTop/ScrollTop.jsx
  src/pages/Main/Components/BookListWrapperGroup/BookListWrapperGroup.jsx
  src/pages/Main/Components/MainTitle/MainTitle.scss
  src/pages/Main/Main.scss
Labels: 리뷰 요청

#39 🚑️ BookEval 컴포넌트 엔드 포인트 수정
  src/components/BookEval/BookEval.jsx
  src/config.jsx
  src/pages/Main/Components/BookListItems/components/ListContentsTitle.jsx
Labels: PR 완료
